version: '2'
services:
  common_server:
    build:
      context: ../
    volumes:
      - ../:/usr/src/app/
    tty: true

  server:
    environment:
      - LOG_LEVEL=DEBUG
    extends:
      service: common_server
    command: bash -c "uvicorn server:app --host 0.0.0.0 --port 80 --debug --workers 4 --reload"
    links:
      - redis
      - postgres
    expose:
      - "80"
    ports:
        - "80:80"

  redis:
    image: redis:2.8.19
    hostname: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fast_api_test
    expose:
    - "5432"
    ports:
      - "5434:5432"